// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOSRqCSDVPGr7kLb3Xr_egdcla-3e-Sj8',
    appId: '1:537865764821:web:e63f169f61fdbd5fde075c',
    messagingSenderId: '537865764821',
    projectId: 'picshare-a3bba',
    authDomain: 'picshare-a3bba.firebaseapp.com',
    storageBucket: 'picshare-a3bba.appspot.com',
    measurementId: 'G-0VMZX4ZR6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuCPomh89wD3lLY3NXrldLf602hfe0NCo',
    appId: '1:537865764821:android:ec2933a446d55ad8de075c',
    messagingSenderId: '537865764821',
    projectId: 'picshare-a3bba',
    storageBucket: 'picshare-a3bba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLaCctSnlUTyO85uylJdWSy8_OX2GQR3A',
    appId: '1:537865764821:ios:ffd9f3b80d72ce43de075c',
    messagingSenderId: '537865764821',
    projectId: 'picshare-a3bba',
    storageBucket: 'picshare-a3bba.appspot.com',
    androidClientId: '537865764821-1j9bu4le92u03kcnqorkcd347p9o20l1.apps.googleusercontent.com',
    iosClientId: '537865764821-kov6poj30uoqkvdi5ai1qgi43pn3mcmr.apps.googleusercontent.com',
    iosBundleId: 'com.example.picShare',
  );
}
